name: Submit for Review
on:
    workflow_dispatch:
        inputs:
            dryRun:
                default: false
                type: boolean
                description: Skip submission and perform a dry run

jobs:
    submit:
        name: Submit
        runs-on: ubuntu-latest
        needs: [validate]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Configure Git
              run: |
                  git config user.email "github-actions@users.noreply.github.com"
                  git config user.name "GitHub Actions"

            - name: Install dependencies
              run: pnpm install

            - name: Bump Version
              id: version
              run: |
                  pnpx changelogen@latest --bump
                  NEW_VERSION=$(node -pe 'require("./package.json").version')
                  echo "newVersion=$NEW_VERSION" >> "$GITHUB_OUTPUT"

            - name: Build and Zip
              run: |
                  pnpm zip
                  pnpm zip:firefox

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  path: .output/*.zip
                  if-no-files-found: error

            - name: Submit
              run: |
                  pnpm wxt submit \
                    --chrome-zip .output/*-chrome.zip \
                    --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip
              env:
                  DRY_RUN: ${{ inputs.dryRun }}
                  CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
                  CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
                  CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
                  CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
                  FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
                  FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                  FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

            - name: Commit and Push
              if: ${{ !inputs.dryRun }}
              run: |
                  git add package.json CHANGELOG.md
                  git commit -am "chore(release): v$NEW_VERSION"
                  git tag v$NEW_VERSION
                  git push
                  git push --tags
              env:
                  NEW_VERSION: ${{ steps.version.outputs.newVersion }}

            - name: Release
              if: ${{ !inputs.dryRun }}
              run: pnpx changelogen@latest gh release ${{ steps.version.outputs.newVersion }} --token ${{ github.token }}
