name: Validate
on:
    workflow_call:
    pull_request:
    push:
        branches:
            - main

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Run Checks
              run: pnpm check

            - name: Build
              run: pnpm build

            - name: Tests
              run: pnpm test:coverage
